# Michell Luiz Costalonga
# Carregando os dados usando scikit-learn

In [1]:
# Importando os módulos

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris as li

X = li().data
Y = li().target

In [2]:
# Imprimindo as variáveis X e Y (10 primeiros valores)
print('Imprimindo X: ')
print(X[:10])
print('\nImprimindo Y: ')
print(Y[:10])


Imprimindo X: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Imprimindo Y: 
[0 0 0 0 0 0 0 0 0 0]


# Exercício 1

Crie um dataframe a partir de X e Y. Primeiro, concatene os arrays numpy. Na sequência, transforme o array final para um dataframe. Altere o nome das colunas para 'X1', 'X2', 'X3', 'X4' e 'target'.

In [3]:
# Concatenando X e Y
data = np.c_[X,Y]

# Criando um dataframe
df = pd.DataFrame(data, columns=['X1', 'X2', 'X3', 'X4', 'target'])

# Imprimindo o dataframe criado
print(df.head())

    X1   X2   X3   X4  target
0  5.1  3.5  1.4  0.2     0.0
1  4.9  3.0  1.4  0.2     0.0
2  4.7  3.2  1.3  0.2     0.0
3  4.6  3.1  1.5  0.2     0.0
4  5.0  3.6  1.4  0.2     0.0


# Exercício 2

Usando o df criado no exercício 1, calcule qual a média da variável 'X2', para cada valor de target. Dica: Use a função groupby no dataframe df para resolver.

In [4]:
# Agrupando por 'target' e realizando a média para cada grupo.

df_target = df.groupby(by='target').apply(lambda x: x.X2.mean())
print(df_target)

target
0.0    3.428
1.0    2.770
2.0    2.974
dtype: float64


# Exercício 3

Construa um dicionário mapeando os valores:

0 - 'A'

1 - 'B'

2 - 'C'

Usando a função map, crie uma coluna nova no dataframe df chamada 'target_2' com o mapeamento feito. Dica: Use a função map como visto em aula.

In [22]:
# Criando um dicionário
dict = {0:'A', 1:'B', 2:'C'}
print(dict)

{0: 'A', 1: 'B', 2: 'C'}


In [26]:
# Imprimindo o dataframe com uma nova coluna chamada 'target_2'
df['target_2'] = Y
print(df.head())

    X1   X2   X3   X4  target  target_2
0  5.1  3.5  1.4  0.2     0.0         0
1  4.9  3.0  1.4  0.2     0.0         0
2  4.7  3.2  1.3  0.2     0.0         0
3  4.6  3.1  1.5  0.2     0.0         0
4  5.0  3.6  1.4  0.2     0.0         0


In [27]:
# Usando a função map, os valores 0, 1 e 2 da coluna 'target_2' foram substituídos por A, B e C, respectivamente.
df.target_2 = df.target_2.map({0:'A', 1:'B', 2:'C'})
print(df.head())

    X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2     0.0        A
1  4.9  3.0  1.4  0.2     0.0        A
2  4.7  3.2  1.3  0.2     0.0        A
3  4.6  3.1  1.5  0.2     0.0        A
4  5.0  3.6  1.4  0.2     0.0        A


# Exercício 4

## 4.1

Filtre o dataframe df onde X1 é maior do que 6 ou target é diferente de 2 e chame-o de df1. Dica: usar os filtros e os operadores vistos em aula.

In [56]:
# Realizando a filtragem dos dados. 
# IMPORTANTE: Não se pode usar os operadores "and" e "or", deve-se usar "&" e "|", respectivamente.
df1 = df[(df.X1 > 6.0) | (df.target != 2.0)]
print(df1.head())

# Número de linhas e colunas do dataframe
print('\nNúmero de linhas e colunas: ')
print(df1.shape)

    X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2     0.0        A
1  4.9  3.0  1.4  0.2     0.0        A
2  4.7  3.2  1.3  0.2     0.0        A
3  4.6  3.1  1.5  0.2     0.0        A
4  5.0  3.6  1.4  0.2     0.0        A

Número de linhas e colunas: 
(141, 6)


# 4.2

Filtre os 15 primeiros índices do dataframe df e chame-o de df2.

In [57]:
# Filtrando os 15 primeiros índices do df
df2 = df[:15]
print(df2.head())

    X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2     0.0        A
1  4.9  3.0  1.4  0.2     0.0        A
2  4.7  3.2  1.3  0.2     0.0        A
3  4.6  3.1  1.5  0.2     0.0        A
4  5.0  3.6  1.4  0.2     0.0        A


## 4.3

Transformando os dataframes df1 e df2 para arrays, multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e imprima o resultado final. Lembre-se de remover a coluna 'target_2' de cada um dos dataframes antes de realizar a multiplicação.

In [58]:
# Removendo as colucas 'target_2' de cada dataframe
df1.drop('target_2', axis=1, inplace=True)
df2.drop('target_2', axis=1, inplace=True)

print('Imprimindo df1 sem a coluna "target_2"')
print(df1.head())
print('\nNúmero de linhas e colunas: ')
print(df1.shape)
print('\nImprimindo df2 sem a coluna "target_2"')
print(df2.head())
print('\nNúmero de linhas e colunas: ')
print(df2.shape)

Imprimindo df1 sem a coluna "target_2"
    X1   X2   X3   X4  target
0  5.1  3.5  1.4  0.2     0.0
1  4.9  3.0  1.4  0.2     0.0
2  4.7  3.2  1.3  0.2     0.0
3  4.6  3.1  1.5  0.2     0.0
4  5.0  3.6  1.4  0.2     0.0

Número de linhas e colunas: 
(141, 5)

Imprimindo df2 sem a coluna "target_2"
    X1   X2   X3   X4  target
0  5.1  3.5  1.4  0.2     0.0
1  4.9  3.0  1.4  0.2     0.0
2  4.7  3.2  1.3  0.2     0.0
3  4.6  3.1  1.5  0.2     0.0
4  5.0  3.6  1.4  0.2     0.0

Número de linhas e colunas: 
(15, 5)


C:\Users\mlcos\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [62]:
# Convertendo os dataframes df1 e df2 para arrays.
array_df1 = df1.values
array_df2 = df2.values.T

# Imprimindo arrays
print('Imprimindo array referente a df1 (5 primeiras linhas): ')
print(array_df1[:5])
print('\nImprimindo array referente a df2 (5 primeiras linhas): ')
print(array_df2[:5])

Imprimindo array referente a df1: 
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]

Imprimindo array referente a df2: 
[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4. ]
 [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2]
 [0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]


In [64]:
# Realizando a multiplicação e imprimindo na tela o resultado.
multiplicacao_arrays = np.dot(array_df1,array_df2)

print('O resultado da multiplicação entre os arrays é: ')
print(multiplicacao_arrays)

O resultado da multiplicação entre os arrays é: 
[[40.26 37.49 37.03 ... 36.96 33.99 45.3 ]
 [37.49 35.01 34.49 ... 34.5  31.63 42.14]
 [37.03 34.49 34.06 ... 34.   31.26 41.66]
 ...
 [48.26 45.75 44.49 ... 44.93 40.28 52.92]
 [51.33 48.53 47.31 ... 47.68 42.87 56.34]
 [51.54 48.6  47.5  ... 47.75 43.03 56.5 ]]


# Exercício 5

## 5.1

Crie uma função que receba um número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays.

In [86]:
# Criando uma função para construir arrays de 0 até N.
def criarArray(N):
    return np.arange(0, N+1, 1);

# Informe o valor de N:

N = int(input('Informe um valor inteiro para N: '))
array = criarArray(N)

# Imprimindo o array:
print('O array gerado é :')
print(array)

Informe um valor inteiro para N: 5
O array gerado é :
[0 1 2 3 4 5]


## 5.2

Crie uma função que receba um array [0, 1, ..., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatóries SEM reposição.

In [90]:
# Criando uma função para receber um array e devolvê-lo com os valores em ordens diferentes e aleatórias.
def arrayAleatorio(arr):
    return np.random.permutation(len(arr))

print('Array original: ')
print(array)

array_aleatorio = arrayAleatorio(array)
print('O array aleatório 1 é: ')
print(array_aleatorio)

Array original: 
[0 1 2 3 4 5]
O array aleatório 1 é: 
[3 0 5 4 1 2]


## 5.3

Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números.

In [91]:
# Criando uma função para criar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1
def criarArrayAleatorio(N):
    return np.random.randint(0, N, size=N)

N = int(input('Digite um valor inteiro para N: '))
arrayAleFunc = criarArrayAleatorio(N)
print('Imprimindo o array criado: ')
print(arrayAleFunc)

Digite um valor inteiro para N: 5
Imprimindo o array criado: 
[2 4 2 0 2]


# Exercício 6

Construa uma função divide_dados:
- Recebe um array X de dimensões quaisquer (n,k) e um parâmetro p entre 0 e 1.
- Divide o array X em duas partes disjuntas de forma aleatória. Ou seja, crie dois novos arrays X1 e X2, onde a dimensão de linhas de X1 somada com a dimensão de linhas de X2 deve ser igual a dimensão de linhas de X.
- Interpertando p como percentual, o tamanho de X1 deve ser p*100% do número de linhas de X, enquanto X2 deve ser o resto.
- Retorne esses dois arrays.

In [232]:
# Criando uma função para dividir os dados de um array de tamanho n,k em dois arrays distintos.
# x é o array de entrada e p é a porcentagem (0 < p < 1).
# A função irá retornar dois arrays X1 e X2, por isso, deve-se declarar duas variáveis ao usar a função.
from sklearn.utils import shuffle

def divide_dados(x, p):
    verificador = False
    try:
        n, k = x.shape
        
    except ValueError:
        verificador = True
        
    if (verificador):
        x = np.random.permutation(len(x))
        X1_len = int(round(len(x)*p, 0))
        X2_len = int(len(x) - X1_len)
        X1 = np.zeros(X1_len)
        X1 = x[:X1_len]
        X2 = np.zeros(X2_len)
        X2 = x[X1_len:]
        return X1, X2
    else:
        X1_len = int(round(len(x)*p, 0))
        X2_len = int(len(x) - X1_len)
        np.random.shuffle(x)
        X1 = np.zeros((X1_len, k))
        X1 = x[:X1_len, ::]
        X2 = np.zeros((X2_len, k))
        X2 = x[X1_len:, ::]
        return X1, X2

In [270]:
# Definindo arryas para teste.
num_linhas = 7
num_colunas = 3
a = np.arange(num_linhas * num_colunas).reshape(num_linhas, num_colunas)
a_lin, a_col = a.shape
b = np.arange(num_linhas * num_colunas)
b_len = len(b)

In [271]:
# Definindo o valor de p (0 < p < 1)

p = 0.5

In [272]:
# Testando com matriz bidimensional (a)

print('Imprimindo a matriz original: ')
print(a)
print('Tamanho original da matriz de entrada: %d, %d' %(a_lin, a_col), end='\n\n')

X1, X2 = divide_dados(a, p)
X1_lin, X1_col = X1.shape
X2_lin, X2_col = X2.shape

print('\nImprimindo a matriz X1: ')
print(X1)
print('\nTamanho da matriz X1: %d, %d' %(X1_lin, X1_col), end='\n\n')

print('\nImprimindo a matriz X2: ')
print(X2)
print('\nTamanho da matriz X2: %d, %d' %(X2_lin, X2_col), end='\n\n')

if (X1_lin + X2_lin == a_lin):
    print('A soma do número de linhas das matrizes X1 e X2 é igual ao número de linhas da matriz original.')
else:
    print('A soma do número de linhas das matrizes X1 e X2 não é igual ao número de linhas da matriz original.')

Imprimindo a matriz original: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
Tamanho original da matriz de entrada: 7, 3


Imprimindo a matriz X1: 
[[ 3  4  5]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]]

Tamanho da matriz X1: 4, 3


Imprimindo a matriz X2: 
[[15 16 17]
 [ 0  1  2]
 [ 9 10 11]]

Tamanho da matriz X2: 3, 3

A soma do número de linhas das matrizes X1 e X2 é igual ao número de linhas da matriz original.


In [273]:
# Testando a função com um array unidimensional.

print('Imprimindo o vetor original: ')
print(a)
print('Tamanho original do vetor de entrada: %d' %(b_len), end='\n\n')

X1, X2 = divide_dados(b, p)
X1_len = len(X1)
X2_len = len(X2)

print('\nImprimindo o vetor X1: ')
print(X1)
print('\nTamanho do vetor X1: %d' %(X1_len), end='\n\n')

print('\nImprimindo a matriz X2: ')
print(X2)
print('\nTamanho da matriz X2: %d' %(X2_len), end='\n\n')

if (X1_len + X2_len == b_len):
    print('A soma do número de elementos de X1 e X2 é igual ao número de elementos do vetor original.')
else:
    print('A soma do número de elementos de X1 e X2 não é igual ao número de linhas do vetor original.')

Imprimindo o vetor original: 
[[ 3  4  5]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]
 [15 16 17]
 [ 0  1  2]
 [ 9 10 11]]
Tamanho original do vetor de entrada: 21


Imprimindo o vetor X1: 
[19  7  8 14  5  6  2 20 18  4]

Tamanho do vetor X1: 10


Imprimindo a matriz X2: 
[ 0 11 17 15  3 16 13 12  9  1 10]

Tamanho da matriz X2: 11

A soma do número de elementos de X1 e X2 é igual ao número de elementos do vetor original.
